In [1]:
import requests, json
import pandas as pd
pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", 500)

url  = 'https://api.deadlock-api.com/v1/matches/metadata'


params = {
    "limit": 500,
    "order_by": "start_time",
    "order_direction": "desc",
    "match_mode": "ranked",
    "include_info": "true",
    "include_more_info": "true",
    "include_objectives": "true",
    "include_mid_boss": "true",
    "include_player_info": "true",
    "include_player_final_stats": "true",
    "include_player_stats": "true",
    "include_player_items": "true",
    "include_player_death_details": "true",
    "hero_ids": "77", # Only get hero ids for apollo
    "format": "json",
}
response = requests.get(url, params=params, timeout=30)
response.raise_for_status()
matches = response.json()

# print(len(matches))
# print(json.dumps(matches, indent=2)[:3000])
df = pd.DataFrame(matches)
df.head()

,match_id,start_time,winning_team,duration_s,match_outcome,match_mode,game_mode,average_badge_team0,average_badge_team1,average_badge,not_scored,rewards_eligible,is_high_skill_range_parties,low_pri_pool,new_player_pool,team_score,match_tracked_stats,team0_tracked_stats,team1_tracked_stats,ranked_type,rank_interval,mid_boss,objectives,players,banned_hero_ids
0,101650753,2026-08-25 19:08:11,Team1,1864,TeamWin,Ranked,Normal,0,0,86,False,True,False,False,False,[],{},{},{},Normal,1,"[{'team_killed': 'Team1', 'team_claimed': 'Tea...","[{'destroyed_time_s': 585, 'creep_damage': 196...","[{'account_id': 159433084, 'hero_id': 8, 'play...",[]
1,101650106,2026-08-25 19:04:26,Team1,1516,TeamWin,Ranked,Normal,0,0,54,False,True,False,False,False,[],{},{},{},Normal,1,[],"[{'destroyed_time_s': 478, 'creep_damage': 217...","[{'account_id': 1188754429, 'hero_id': 20, 'pl...",[]
2,101649967,2026-08-25 19:03:36,Team1,1716,TeamWin,Ranked,Normal,0,0,94,False,True,False,False,False,[],{},{},{},Normal,1,"[{'team_killed': 'Team1', 'team_claimed': 'Tea...","[{'destroyed_time_s': 675, 'creep_damage': 136...","[{'account_id': 17081245, 'hero_id': 31, 'play...",[]
3,101649825,2026-08-25 19:02:42,Team0,1929,TeamWin,Ranked,Normal,0,0,81,False,True,False,False,False,[],{},{},{},Normal,1,"[{'team_killed': 'Team1', 'team_claimed': 'Tea...","[{'destroyed_time_s': 535, 'creep_damage': 183...","[{'account_id': 105624006, 'hero_id': 77, 'pla...",[]
4,101649288,2026-08-25 18:59:38,Team0,2030,TeamWin,Ranked,Normal,0,0,86,False,True,False,False,False,[],{},{},{},Normal,1,"[{'team_killed': 'Team0', 'team_claimed': 'Tea...","[{'destroyed_time_s': 508, 'creep_damage': 204...","[{'account_id': 1580717306, 'hero_id': 18, 'pl...",[]

In [2]:
match = matches[0]
player = match["players"]
player_df = pd.DataFrame(player)
player_df.head(1)

,account_id,hero_id,player_slot,team,hero_build_id,kills,deaths,assists,net_worth,last_hits,denies,ability_points,assigned_lane,player_level,abandon_match_time_s,player_tracked_stats,accolades,hero_xp_rewards,player_match_outcome,player_rank_initial_display_rank,player_rank_initial_flat_progress,player_rank_final_flat_progress,player_rank_desired_progress_change,player_rank_initial_calibration_games,player_rank_initial_demotion_protection_games,player_rank_consumed_demotion_protection,player_rank_initial_win_streak,items,stats,final_stats,death_details,mvp_rank
0,159433084,8,3,Team0,0,2,9,1,26698,156,19,24,6,28,0,{},"[{'accolade_id': 10, 'accolade_stat_value': 19...","[{'hero_id': 8, 'xp_grant': 50, 'reason': 'Los...",Loss,86,55470,55170,-300,0,2,False,0,"[{'game_time_s': 13, 'item_id': 3133377790, 'u...","[{'time_stamp_s': 180, 'net_worth': 1821, 'gol...","{'ability_kills': 1, 'ability_points': 24, 'ab...","[{'game_time_s': 371, 'killer_player_slot': 8,...",NaN

In [3]:
player_rows = []
for match in matches:
    for p in match["players"]:
        player_rows.append(p)

players_df = pd.DataFrame(player_rows)
players_df.head(1)

,account_id,hero_id,player_slot,team,hero_build_id,kills,deaths,assists,net_worth,last_hits,denies,ability_points,assigned_lane,player_level,abandon_match_time_s,player_tracked_stats,accolades,hero_xp_rewards,player_match_outcome,player_rank_initial_display_rank,player_rank_initial_flat_progress,player_rank_final_flat_progress,player_rank_desired_progress_change,player_rank_initial_calibration_games,player_rank_initial_demotion_protection_games,player_rank_consumed_demotion_protection,player_rank_initial_win_streak,items,stats,final_stats,death_details,mvp_rank
0,159433084,8,3,Team0,0,2,9,1,26698,156,19,24,6,28,0,{},"[{'accolade_id': 10, 'accolade_stat_value': 19...","[{'hero_id': 8, 'xp_grant': 50, 'reason': 'Los...",Loss,86,55470,55170,-300,0,2,False,0,"[{'game_time_s': 13, 'item_id': 3133377790, 'u...","[{'time_stamp_s': 180, 'net_worth': 1821, 'gol...","{'ability_kills': 1, 'ability_points': 24, 'ab...","[{'game_time_s': 371, 'killer_player_slot': 8,...",NaN

In [4]:
stat_list = players_df['stats'][0]
stat = stat_list[0]
stat.keys()

dict_keys(['time_stamp_s', 'net_worth', 'gold_player', 'gold_player_orbs', 'gold_lane_creep_orbs', 'gold_neutral_creep_orbs', 'gold_boss', 'gold_boss_orb', 'gold_treasure', 'gold_denied', 'gold_death_loss', 'gold_lane_creep', 'gold_neutral_creep', 'kills', 'deaths', 'assists', 'creep_kills', 'neutral_kills', 'possible_creeps', 'creep_damage', 'player_damage', 'neutral_damage', 'boss_damage', 'denies', 'player_healing', 'ability_points', 'self_healing', 'player_barriering', 'teammate_healing', 'teammate_barriering', 'self_damage', 'bullet_kills', 'melee_kills', 'ability_kills', 'headshot_kills', 'player_damage_taken', 'max_health', 'weapon_power', 'tech_power', 'shots_hit', 'shots_missed', 'damage_absorbed', 'absorption_provided', 'hero_bullets_hit', 'hero_bullets_hit_crit', 'heal_prevented', 'heal_lost', 'damage_mitigated', 'level'])

In [5]:
item_list = players_df['items'][0]
item = item_list[0]
item.keys()

dict_keys(['game_time_s', 'item_id', 'upgrade_id', 'sold_time_s', 'flags', 'imbued_ability_id', 'upgrade_info', 'net_worth_at_buy'])

In [6]:
all_items = []

for items in players_df["items"]:
    for item in items:
        all_items.append(item)

items_df = pd.DataFrame(all_items)
items_df.head()

,game_time_s,item_id,upgrade_id,sold_time_s,flags,imbued_ability_id,upgrade_info,net_worth_at_buy
0,13,3133377790,0,0,0,0,65537,26698
1,49,3133377790,1895841343,0,0,0,196609,26698
2,58,1009965641,1,0,0,0,65537,26698
3,100,2142734020,0,0,0,0,65537,26698
4,179,3776945997,1,1048,1,0,65537,26698

In [13]:
url = 'https://api.deadlock-api.com/v1/assets/items'
response = requests.get(url, timeout=30)
response.raise_for_status()
items = response.json()

mapping = {}
for item in items:
    if item['type'] == 'upgrade' and item.get('shopable', False):
        mapping[item["id"]] = item["name"]

items_df["item_name"] = items_df["item_id"].map(mapping)

In [15]:
items_df.head()

,game_time_s,item_id,upgrade_id,sold_time_s,flags,imbued_ability_id,upgrade_info,net_worth_at_buy,item_name,is_shop_item
0,13,3133377790,0,0,0,0,65537,26698,NaN,False
1,49,3133377790,1895841343,0,0,0,196609,26698,NaN,False
2,58,1009965641,1,0,0,0,65537,26698,Monster Rounds,True
3,100,2142734020,0,0,0,0,65537,26698,NaN,False
4,179,3776945997,1,1048,1,0,65537,26698,Extra Charge,True

In [8]:
# Restrict to hero 77 and wins only
#
# fil_hero77_won= players_df[(players_df["hero_id"] == 77) & (players_df["won"])]
# items_series = fil_hero77_won["items"]
# items_df = pd.DataFrame(items_series)
#
# all_items = []
# for idx, item_group in items_df['items'].items():
#     for item in item_group:
#         item = dict(item)
#         item['match_id'] = idx
#         all_items.append(item)
#
# df_items = pd.DataFrame(all_items)
# df_items

In [9]:
# import http.client, json
#
# conn = http.client.HTTPSConnection("api.deadlock-api.com")
# conn.request("GET", "/v1/assets/items")  # add ?client_version=6518 to pin a patch
# items = json.loads(conn.getresponse().read())
# items_assets_df = pd.DataFrame(items)
# items_assets_df.head(1)

In [10]:
url = "https://api.deadlock-api.com/v1/analytics/item-stats"

params = {
    "hero_id": 77,
    "match_mode": "ranked",
}
response = requests.get(url, timeout=30)
response.raise_for_status()
item_stats = response.json()

# print(len(matches))
# print(json.dumps(matches, indent=2)[:3000])
item_stats_df = pd.DataFrame(item_stats)
item_stats_df.head()


item_stats_df["item_name"] = item_stats_df["item_id"].map(mapping)
item_stats_df.head(1)

,item_id,bucket,wins,losses,matches,players,avg_buy_time_s,avg_sell_time_s,avg_buy_time_relative,avg_sell_time_relative,item_name
0,7409189,0,4032837,3908356,7941193,770957,843.630688,1798.967099,36.880477,73.498384,Improved Spirit

In [11]:
wins_mean = item_stats_df["wins"].mean()
item_stats_df["abv_avr"] = item_stats_df["wins"] >= wins_mean
items_df["is_shop_item"] = items_df["item_name"].notna()
item_stats_df["is_shop_item"] = items_df["item_name"].notna()

df_items_shopable = (item_stats_df[(item_stats_df["is_shop_item"]) & (item_stats_df["abv_avr"])])

# sort
df_items_shopable.sort_values("win_rate", ascending=False, inplace=True)

y = df_items_shopable["win_rate"]
x = df_items_shopable["item_name"]
z = df_items_shopable["avg_buy_time_s"]


import plotly.express as px


df = px.data.iris()
fig = px.scatter(df, x=z, y=y, color=x, symbol=x)
fig.update_layout(xaxis_title="Avg Buy Time Seconds", yaxis_title="Win Rate")
fig.show()

KeyError: 'win_rate'