In [56]:
import pandas as pd

practice_df = pd.DataFrame({
    'player_name': ['Alice', 'Bob', 'Carol'],
    'match_id': [1001, 1002, 1003],
    'purchases': [
        [{'time': 0, 'item': 'sword', 'cost': 100}, {'time': 30, 'item': 'shield', 'cost': 150}],
        [{'time': 5, 'item': 'potion', 'cost': 20}],
        [{'time': 10, 'item': 'bow', 'cost': 200}, {'time': 45, 'item': 'arrow', 'cost': 10}, {'time': 60, 'item': 'quiver', 'cost': 50}],
    ]
})

practice_df

  player_name  match_id                                          purchases
0       Alice      1001  [{'time': 0, 'item': 'sword', 'cost': 100}, {'...
1         Bob      1002        [{'time': 5, 'item': 'potion', 'cost': 20}]
2       Carol      1003  [{'time': 10, 'item': 'bow', 'cost': 200}, {'t...

In [57]:
exploded = practice_df.explode('purchases').reset_index(drop=True)
exploded['purchases']

0      {'time': 0, 'item': 'sword', 'cost': 100}
1    {'time': 30, 'item': 'shield', 'cost': 150}
2      {'time': 5, 'item': 'potion', 'cost': 20}
3       {'time': 10, 'item': 'bow', 'cost': 200}
4      {'time': 45, 'item': 'arrow', 'cost': 10}
5     {'time': 60, 'item': 'quiver', 'cost': 50}
Name: purchases, dtype: object

In [58]:
df = pd.json_normalize(exploded['purchases'])

In [59]:
fixed = exploded.join(df)
fixed

,player_name,match_id,purchases,time,item,cost
0,Alice,1001,"{'time': 0, 'item': 'sword', 'cost': 100}",0,sword,100
1,Alice,1001,"{'time': 30, 'item': 'shield', 'cost': 150}",30,shield,150
2,Bob,1002,"{'time': 5, 'item': 'potion', 'cost': 20}",5,potion,20
3,Carol,1003,"{'time': 10, 'item': 'bow', 'cost': 200}",10,bow,200
4,Carol,1003,"{'time': 45, 'item': 'arrow', 'cost': 10}",45,arrow,10
5,Carol,1003,"{'time': 60, 'item': 'quiver', 'cost': 50}",60,quiver,50